# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gpt2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngpt2.proto\x12\x04gpt2\"M\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nmax_length\x18\x02 \x01(\x05\x12\x1c\n\x14num_return_sequences\x18\x03 \x01(\x05\"\x1c\n\x0cTextResponse\x12\x0c\n\x04text\x18\x01 \x03(\t2D\n\x0b\x43hatService\x12\x35\n\x0cGenerateText\x12\x11.gpt2.TextRequest\x1a\x12.gpt2.TextResponseB\x11Z\x0fhnaderi268/gpt2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gpt2_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\017hnaderi268/gpt2'
  _globals['_TEXTREQUEST']._serialized_start=20
  _globals['_TEXTREQUEST']._serialized_end=97
  _globals['_TEXTRESPONSE']._serialized_start=99
  _globals['_TEXTRESPONSE']._serialized_end=127
  _globals['_CHATSERVICE']._serialized_start=129
  _globals['_CHATSERVICE']._serialized_end=197
# @@protoc_insertion_point(module_scope)
